// ESLint v10 flat config. Replaces the legacy .eslintrc.cjs (frontend) and
// lambda/.eslintrc.cjs (Lambda .mjs files). One file, three lint domains:
//
//   - src/**/*.{ts,tsx}      — TypeScript + React Hooks + React Refresh
//   - lambda/**/*.mjs         — Node + the awslambda runtime global
//   - scripts/**/*.{js,mjs}   — Node build/codegen scripts
//
// The `files` glob on each config object scopes its rules. Global ignores
// live in a top-level `ignores` block.

import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import globals from 'globals';

export default [
  // Global ignores — must be the only key in this config object to apply globally.
  {
    ignores: [
      'dist/**',
      'coverage/**',
      'node_modules/**',
      'lambda/**/node_modules/**',
      'lambda/**/function.zip',
      'lambda/**/__fixtures__/**',
      'cypress/**',
      '.claude/**',
      // Generated by build/codegen scripts; ignore to keep lint deterministic.
      'src/data/generatedEpisodes.json',
      // Plain JS in repo root we don't lint (e.g. config files in postcss/tailwind layers).
      'postcss.config.js',
      'tailwind.config.js',
    ],
  },

  // Recommended baseline for every JS/TS file.
  js.configs.recommended,

  // Frontend: src/**/*.{ts,tsx}
  ...tseslint.configs.recommended.map((config) => ({
    ...config,
    files: ['src/**/*.{ts,tsx}'],
  })),
  {
    files: ['src/**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.es2020,
      },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    linterOptions: {
      reportUnusedDisableDirectives: 'error',
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': [
        'warn',
        { allowConstantExport: true },
      ],
      // React Compiler-derived strict rules introduced in eslint-plugin-react-hooks v6/v7.
      // These flag real anti-patterns (synchronous setState inside useEffect, refs read
      // during render, components defined inside other components, locals mutated after
      // render). Adopting them is a meaningful refactor across data-fetching surfaces
      // (Blog, BlogPost, Chat, AskTheVector) and is intentionally deferred to a focused
      // follow-up so this PR stays scoped to the ESLint v10 + flat-config migration.
      // Re-enable each one (and fix its callers) incrementally.
      'react-hooks/set-state-in-effect': 'off',
      'react-hooks/refs': 'off',
      'react-hooks/immutability': 'off',
      // Enabled in this PR (fix/react-hooks-static-components): the only
      // call site, GenerativeBlocks.tsx's Comparison.Column, has been
      // hoisted to module scope.
      'react-hooks/static-components': 'error',
    },
  },

  // Lambda: ESM .mjs handlers with the awslambda runtime global.
  {
    files: ['lambda/**/*.mjs'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        ...globals.node,
        awslambda: 'readonly',
      },
    },
    linterOptions: {
      reportUnusedDisableDirectives: 'error',
    },
    rules: {
      'no-console': 'off',
      'no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },

  // Build/codegen scripts: Node ESM + CJS.
  {
    files: ['scripts/**/*.{js,mjs,cjs}', 'vitest.config.ts', 'cypress.config.ts'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: { ...globals.node },
    },
  },
];
